### ISSUE TITLE
Cast not returning decrypted values

### ISSUE THREAD

**Issue by heyaj19** [roelofr/laravel-encryption-cast#1]
Everything works great but I cannot get the decrypted values back. Other than setting casts is there anything else that needs to be done?

**Comment by heyaj19** [comment]
@roelofr  Was wondering if you had a chance to look at this ?

**Comment by roelofr** [comment]
I'll look into this tomorrow (CEST), but I missed it the first time somehow

**Comment by heyaj19** [comment]
@roelofr  ok thank you

**Comment by roelofr** [comment]
I couldn't replicate the issue, until I tried to cast from a custom cast to the database. Working on a fix now.

**Comment by heyaj19** [comment]
@roelofr  just sharing my code I am not using any custom cast and still hd an issue where the decrypted values are not returned. I tried 


`   
       <?php
       declare(strict_types=1);
        namespace App;

     use Illuminate\Database\Eloquent\Model;

       use App\Http\Abstracts\UuidModel;
       use Illuminate\Support\Str;
       use Roelofr\EncryptionCast\Casts\EncryptedAttribute;
       class IntakeForm extends UuidModel
     {  



          protected $guarded=[];

    /**
     * @inheritDoc
     */
    protected $casts = [
        'active' =>'boolean' ,
		'address'=>EncryptedAttribute::class,
        'phone' => EncryptedAttribute::class
    ];
     /**
     * Get the owning imageable model.
     */
    public function intakeformable()
    {
        return $this->morphTo();
    }


}`


`[2020-08-26 18:58:31] dev.ERROR: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) at /Users//code/instawalkin/vendor/roelofr/laravel-encryption-cast/src/Casts/EncryptedAttribute.php:17)
[stacktrace]
#0 /Users//code/instawalkin/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/Users/...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Roelofr\\\\Encrypt...')`

**Comment by heyaj19** [comment]
Just wondering if I need to add getAttribute and setAttribute as well?

**Comment by roelofr** [comment]
Are you running PHP 7.4 or PHP 8.0? The line mentioned will throw an exception on PHP 7.3 and older as I'm using [typed properties](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.typed-properties).

Edit: I am wondering, are you running an older PHP with a `platform` set in your `composer.json`, or using `--ignore-platform-reqs`, since you should not be able to install this library on PHP 7.3 and older.

**Comment by heyaj19** [comment]
I actually installed 7.4.9 - But my composer was not referring to two paths for PHP 

```json
"require": {
        "php": "^7.3.6"}


And  "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "7.4.9"
        }
```

I did a `composer dumpautoload` after changing both too 7.4.9 and still am getting an error

**Comment by heyaj19** [comment]
Also deleted the composer lock file and did a composer install

**Comment by heyaj19** [comment]
Fixed, had to do a composer global install and restart my machine

**Comment by roelofr** [comment]
I... I don't know how you have php installed via composer as you're insinuating, but I can recommend to not use a [`config.platform`][1] property unless you __really__ need one. It's safer to rely on Composer figuring it out for you and just use a `"php": ">=7.4"` entry in your `require` group.

[1]: https://getcomposer.org/doc/06-config.md#platform

**Comment by heyaj19** [comment]
ah ok ill change it thaks for the advice
