### ISSUE TITLE
Find database

### ISSUE THREAD

**Issue by diego-pealmeida** [roelofr/laravel-encryption-cast#3]
How to perform a database search for encrypted data? Because if I try to search for an unencrypted word, and in the database it is encrypted, the search has no result

**Comment by roelofr** [comment]
You can't search the encrypted data without first decrypting it.

Take, for example, this `php artisan tinker` call. I simply invoked the method twice:

```
>>> Crypt::encryptString('steve');
=> "eyJpdiI6IjRsU0l1MStFcFpxUlVcL25FUktvUXRBPT0iLCJ2YWx1ZSI6IlwvZEdQN3Fub2ZwOSt1d1ltM1g4VitnPT0iLCJtYWMiOiI3NDlkYjg3MjA0YTZmZDA1OGE2NDRlNGMxM2FiYTlkNGY2NDVjMWE4YWFlMzAzMWRjOTE2ZWEyMDVlYTVjY2M4In0="
>>> Crypt::encryptString('steve');
=> "eyJpdiI6Ilwva2FNVXJwNmd4SkdRS3ZnK2hjNyt3PT0iLCJ2YWx1ZSI6InVLaHB0dzZQa3B2dlgyMGlSQ1llVWc9PSIsIm1hYyI6ImQxM2UxYTc3Yzc2NTZjYWYwYmI3ZDk2ZjdjZTM3YmI4MTNkYzE3N2VkN2VjYWMzYWNiNjdmY2E5MjdiOTA2MGMifQ=="
```

The only real way to search the data, is to get a `Model::cursor()` or `Model::chunk(100, function () { … })`, and iterate through each item. If you can scope by a visible field, that'd make the iteration shorter.
